### ISSUE TITLE
Data From Database

### ISSUE THREAD

**Issue by mhtchong1989** [cjsaylor/gchart#3]
How do you put the data from the $this->Model->find to the chart?

**Comment by cjsaylor** [comment]
@mhtchong1989 You would need to get that data into your controller and then expose it to the view via `set`.

Something like:

``` php

<?php

class SomeController extends AppController {

  public function index() {
    $data = $this->YourModel->find(
      //...
    );
    $this->set(compact('data'));
  }

}
```

Then in your view `$data` would be available exactly like the example on the readme.
